### ISSUE TITLE
[Featurerequest] Compatibilty with the new HUD-System of TTT2

### ISSUE THREAD

**Issue by TimGoll** [DoctorJew/TTT-Clairvoyancy#1]
TTT2 introduces a new hud system. There is not much todo to support this update.

**Comment by dhkatz** [comment]
I suppose I could take a look

**Comment by TimGoll** [comment]
Nevermind, one of our players has ported it to TTT2

**Comment by dhkatz** [comment]
> Nevermind, one of our players has ported it to TTT2

You could always have the player create a pull request and I will update the workshop version immediately.

**Comment by TimGoll** [comment]
I'll ask him

**Comment by dhkatz** [comment]
I added support for TTT2 in the original addon.
